version: '3'

services:
  portainer:
    image: "portainer/portainer-ce:alpine"
    restart: always
    environment:
      - "VIRTUAL_HOST=${HOST}"
      - "LETSENCRYPT_HOST=${HOST}"
      - "VIRTUAL_PORT=9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
networks:
  default:
    external:
      name: proxy-network
